[package]
name = "oom-monitor"
version = "0.1.0"
authors = ["Tormod G. Hellen <tormod@mbr-targeting.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "*"
chrono = "*"
regex = "*"

[build]
target = "x86_64-unknown-linux-musl"