#!/bin/bash -eu

cargo build --release --target x86_64-unknown-linux-musl

rm *.deb -f

fpm -s dir \
   -t deb \
   --iteration 1 \
   --architecture x86_64 \
   --deb-ignore-iteration-in-dependencies \
   --name oom-monitor \
   --verbose \
   --version 1.2.4 \
   --depends systemd \
   --deb-systemd ./oom-monitor.service \
   ./target/x86_64-unknown-linux-musl/release/oom-monitor=/usr/bin/oom-monitor